Added steamcmd build container for first build step
mikecarey134/python-projects pull request #7
Opened 2024-04-24 08:08 UTC by mikecarey134

2024-04-24 11:09 UTC, lamartina requested changes
Added comments.

2024-04-24 11:09 UTC, lamartina commented on docker/valheim/Dockerfile
> +FROM ubuntu:23.10
Why, the switch to Ubuntu from debian?

2024-04-24 11:09 UTC, lamartina commented on docker/valheim/run.sh
> +docker run -d -p 2456:2458 -v valheim:/server --name valheim valheim
Different port?

2024-04-24 17:10 UTC, mikecarey134 commented on docker/valheim/Dockerfile
> +FROM ubuntu:23.10
was testing functionality of steamcmd so far I can get the server running but cant connect to it

2024-04-24 17:10 UTC, mikecarey134 commented on docker/valheim/run.sh
> +docker run -d -p 2456:2458 -v valheim:/server --name valheim valheim
range 2456-2458

2024-04-24 17:10 UTC, mikecarey134 commented on docker/valheim/run.sh
> +docker run -d -p 2456:2458 -v valheim:/server --name valheim valheim
nvm I fucked this up lol

2024-04-24 17:13 UTC, lamartina commented on docker/valheim/run.sh
> +docker run -d -p 2456:2458 -v valheim:/server --name valheim valheim
Looks better now lol

2024-04-24 17:14 UTC, mikecarey134 commented on docker/valheim/run.sh
> +docker run -d -p 2456:2458 -v valheim:/server --name valheim valheim
fixed this in latest push

2024-04-24 23:42 UTC, mikecarey134 reviewed
Updated for your review

2024-04-24 23:46 UTC, lamartina approved these changes
Loooooks guuda like cheese

2024-04-25 03:15 UTC, lamartina reviewed
Looks good

2024-05-16 22:52 UTC, merged